version: '3.4'
services:
  scoutdemoservice.core:
    image: '${DOCKER_REGISTRY-}scoutdemoservicecore'
    build:
      context: .
      dockerfile: ScoutDemoService.Core/Dockerfile
    links: 
        - scoutdb
    container_name: scoutdemoservice.core
  scoutdb:
    image: 'mysql:latest'
    container_name: scoutdb
    environment:
      - MYSQL_ROOT_PASSWORD=scoutdemopassword1234!
    volumes:
            - 'G:\Github\ScoutDemoService\ScoutDemoService.Core\MySqlInit:/docker-entrypoint-initdb.d'
