version: '3.4'
services:
  scoutdemoservice.core:
    image: '${DOCKER_REGISTRY-}scoutdemoservicecore'
    build:
      context: .
      dockerfile: ScoutDemoService.Core/Dockerfile
    links: 
        - scoutdb
    ports:
      - "8083:80"
      - "8082:443"
    container_name: scoutdemoservice.core
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8082
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  scoutdb:
    image: 'mysql:latest'
    container_name: scoutdb
    environment:
      - MYSQL_ROOT_PASSWORD=scoutdemopassword1234!
    volumes:
            - 'G:\Github\ScoutDemoService\ScoutDemoService.Core\MySqlInit:/docker-entrypoint-initdb.d'
